#region enums
public enum Event_Type
{
    TRIGGER_EVENT,
    FLOAT_CHANGE,
    FLOAT_SET,
    JOB_APPLY,
    JOB_FIRED,
    DEBUG_COLOR_CHANGE,
    CAMERA_TURN,
    STATS_CALL,
    UI_ELEMENT_CALL,
    WELFARE_HAS_ENDED,
    WELFARE_HAS_BEEN_APPLIED,
    JOB_REGISTERED_TO_PLAYER,
    PLAYER_WANTS_WELFARE,
    PLAYER_LEASES_HOME,
    FLAG_FIRE,
    EVENT_REGISTER
}
#endregion